# pyTorch的基础知识

Tensor是pyTorch中的重要数据结构

In [222]:
import torch

In [223]:
torch.__version__

'0.4.0'

In [224]:
#  构建 5x3 矩阵，只是分配了空间，未初始化
x = torch.Tensor(5, 3)
x

tensor([[ 0.0000e+00,  0.0000e+00,  1.2163e-42],
        [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
        [-1.2196e+32,  6.9364e-43,  0.0000e+00],
        [ 0.0000e+00,  7.0065e-45,  0.0000e+00],
        [-1.2197e+32,  6.9364e-43,  0.0000e+00]])

In [225]:
x = torch.rand(5, 3)
x

tensor([[ 0.3518,  0.6970,  0.3894],
        [ 0.9692,  0.4398,  0.0020],
        [ 0.9747,  0.2134,  0.9630],
        [ 0.6245,  0.9902,  0.2900],
        [ 0.5637,  0.4301,  0.9979]])

In [226]:
 x.size(), x.shape, x.size(0), x.size()[1]  # 查看x的形状，行，列

(torch.Size([5, 3]), torch.Size([5, 3]), 5, 3)

In [227]:
y = torch.rand(5, 3)
y

tensor([[ 0.7773,  0.4528,  0.8945],
        [ 0.0800,  0.0656,  0.4296],
        [ 0.9672,  0.7910,  0.7132],
        [ 0.8268,  0.9885,  0.0143],
        [ 0.3792,  0.0680,  0.9367]])

In [228]:
# 加法的几种写法
x + y

tensor([[ 1.1291,  1.1498,  1.2840],
        [ 1.0492,  0.5053,  0.4317],
        [ 1.9419,  1.0044,  1.6762],
        [ 1.4513,  1.9787,  0.3043],
        [ 0.9430,  0.4981,  1.9346]])

In [229]:
torch.add(x, y)

tensor([[ 1.1291,  1.1498,  1.2840],
        [ 1.0492,  0.5053,  0.4317],
        [ 1.9419,  1.0044,  1.6762],
        [ 1.4513,  1.9787,  0.3043],
        [ 0.9430,  0.4981,  1.9346]])

In [230]:
result = torch.Tensor()
torch.add(x, y, out=result)

tensor([[ 1.1291,  1.1498,  1.2840],
        [ 1.0492,  0.5053,  0.4317],
        [ 1.9419,  1.0044,  1.6762],
        [ 1.4513,  1.9787,  0.3043],
        [ 0.9430,  0.4981,  1.9346]])

In [231]:
result

tensor([[ 1.1291,  1.1498,  1.2840],
        [ 1.0492,  0.5053,  0.4317],
        [ 1.9419,  1.0044,  1.6762],
        [ 1.4513,  1.9787,  0.3043],
        [ 0.9430,  0.4981,  1.9346]])

In [232]:
y.add_(x)

tensor([[ 1.1291,  1.1498,  1.2840],
        [ 1.0492,  0.5053,  0.4317],
        [ 1.9419,  1.0044,  1.6762],
        [ 1.4513,  1.9787,  0.3043],
        [ 0.9430,  0.4981,  1.9346]])

In [233]:
x.copy_(y)

tensor([[ 1.1291,  1.1498,  1.2840],
        [ 1.0492,  0.5053,  0.4317],
        [ 1.9419,  1.0044,  1.6762],
        [ 1.4513,  1.9787,  0.3043],
        [ 0.9430,  0.4981,  1.9346]])

##### 注意，函数名后面带下划线_ 的函数会修改Tensor本身。例如，x.add_(y)和x.t_()会改变 x，但x.add(y)和x.t()返回一个新的Tensor， 而x不变。

In [234]:
# 使用torch.view对tensor进行变形， -1 表示自适应
x = torch.randn(4,4)
x

tensor([[-0.5998, -0.5036, -0.9585,  0.2111],
        [ 0.5805, -0.0628,  0.3313, -1.2722],
        [-0.2446,  0.1221,  0.0191,  1.0641],
        [-1.7733,  0.4213,  1.2326, -0.3900]])

In [235]:
y= x.view(16)   
y

tensor([-0.5998, -0.5036, -0.9585,  0.2111,  0.5805, -0.0628,  0.3313,
        -1.2722, -0.2446,  0.1221,  0.0191,  1.0641, -1.7733,  0.4213,
         1.2326, -0.3900])

In [236]:
z1 = x.view(-1, 8)
z1

tensor([[-0.5998, -0.5036, -0.9585,  0.2111,  0.5805, -0.0628,  0.3313,
         -1.2722],
        [-0.2446,  0.1221,  0.0191,  1.0641, -1.7733,  0.4213,  1.2326,
         -0.3900]])

In [237]:
z2 = x.view(4, -1)
z2

tensor([[-0.5998, -0.5036, -0.9585,  0.2111],
        [ 0.5805, -0.0628,  0.3313, -1.2722],
        [-0.2446,  0.1221,  0.0191,  1.0641],
        [-1.7733,  0.4213,  1.2326, -0.3900]])

In [238]:
w = x.view(-1)  # 等价于x.view(16) 
w

tensor([-0.5998, -0.5036, -0.9585,  0.2111,  0.5805, -0.0628,  0.3313,
        -1.2722, -0.2446,  0.1221,  0.0191,  1.0641, -1.7733,  0.4213,
         1.2326, -0.3900])

##### Tensor和Numpy的数组之间的互操作非常容易且快速. Torch Tensor 和 NumPy 数组将会共享它们的实际的内存位置, 改变一个另一个也会跟着改

In [242]:
# 转换 Torch Tensor 数组为 Numpy
a = torch.ones(5)
a

tensor([ 1.,  1.,  1.,  1.,  1.])

In [243]:
b = a.numpy()
b

array([ 1.,  1.,  1.,  1.,  1.], dtype=float32)

In [244]:
# 转换 NumPy 数组为 Torch Tensor
a = numpy.ones(5)

In [245]:
b = torch.from_numpy(a)
b

tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)

In [246]:
b.add_(1)

tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)

In [247]:
a, b   # a和b 均改变

(array([ 2.,  2.,  2.,  2.,  2.]),
 tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64))

##### 如果你想获取某一个元素的值，可以使用scalar.item。 直接tensor[idx]得到的还是一个tensor: 一个0-dim 的tensor，一般称为scalar.

In [248]:
tensor = torch.tensor([2])
tensor

tensor([ 2])

In [249]:
scalar = tensor.item()
scalar

2

In [250]:
#  在不支持CUDA的机器下，下一步还是在CPU上运行
a = torch.ones(5)
b = torch.zeros(5)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
a = a.to(device)
b = b.to(device)
c = a + b
a, b, c

(tensor([ 1.,  1.,  1.,  1.,  1.], device='cuda:0'),
 tensor([ 0.,  0.,  0.,  0.,  0.], device='cuda:0'),
 tensor([ 1.,  1.,  1.,  1.,  1.], device='cuda:0'))

### autograd: 自动微分

In [253]:
# 为tensor设置 requires_grad 标识，代表着需要求导数
a = torch.ones((2, 2), requires_grad=True)
a

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [254]:
b = a.sum()
b

tensor(4.)

In [255]:
b.grad_fn

In [256]:
b.backward()

In [257]:
a.grad

tensor([[ 1.,  1.],
        [ 1.,  1.]])

##### 注意：grad在反向传播过程中是累加的(accumulated)，这意味着每一次运行反向传播，梯度都会累加之前的梯度，所以反向传播之前需把梯度清零。

In [258]:
b.backward()
a.grad

tensor([[ 2.,  2.],
        [ 2.,  2.]])

In [259]:
b.backward()
a.grad

tensor([[ 3.,  3.],
        [ 3.,  3.]])

In [268]:
# 以下划线结束的函数是inplace操作，会修改自身的值，就像add_
a.grad.zero_()    # 梯度清零   等价于 a.grad.data.zero_()

tensor([[ 0.,  0.],
        [ 0.,  0.]])

In [269]:
b.backward()
a.grad

tensor([[ 1.,  1.],
        [ 1.,  1.]])